#BeginMacro(L)
(0)
#EndMacro
#BeginMacro(S)
(1)
#EndMacro
#BeginMacro(A)
(2)
#EndMacro
#BeginMacro(B)
(3)
#EndMacro
#BeginMacro(C)
(4)
#EndMacro
#BeginMacro(G)
(5)
#EndMacro
#BeginMacro(F)
(6)
#EndMacro
#BeginMacro(D)
(7)
#EndMacro

%Transitions for current state D
#BeginMacro(isD)
((0, 0)=#macro(D))
#EndMacro
#BeginMacro(isLeftD)
((0, -1)=#macro(D))
#EndMacro
#BeginMacro(isRightD)
((0, 1)=#macro(D))
#EndMacro

#BeginMacro(isS)
((0, 0)=#macro(S))
#EndMacro
#BeginMacro(isLeftS)
((0, -1)=#macro(S))
#EndMacro
#BeginMacro(isRightS)
((0, 1)=#macro(S))
#EndMacro

#BeginMacro(isL)
((0, 0)=#macro(L))
#EndMacro
#BeginMacro(isLeftL)
((0, -1)=#macro(L))
#EndMacro
#BeginMacro(isRightL)
((0, 1)=#macro(L))
#EndMacro

#BeginMacro(isA)
((0, 0)=#macro(A))
#EndMacro
#BeginMacro(isLeftA)
((0, -1)=#macro(A))
#EndMacro
#BeginMacro(isRightA)
((0, 1)=#macro(A))
#EndMacro

#BeginMacro(isB)
((0, 0)=#macro(B))
#EndMacro
#BeginMacro(isLeftB)
((0, -1)=#macro(B))
#EndMacro
#BeginMacro(isRightB)
((0, 1)=#macro(B))
#EndMacro

#BeginMacro(isC)
((0, 0)=#macro(C))
#EndMacro
#BeginMacro(isLeftC)
((0, -1)=#macro(C))
#EndMacro
#BeginMacro(isRightC)
((0, 1)=#macro(C))
#EndMacro

#BeginMacro(isG)
((0, 0)=#macro(G))
#EndMacro
#BeginMacro(isLeftG)
((0, -1)=#macro(G))
#EndMacro
#BeginMacro(isRightG)
((0, 1)=#macro(G))
#EndMacro

#BeginMacro(isF)
((0, 0)=#macro(F))
#EndMacro
#BeginMacro(isLeftF)
((0, -1)=#macro(F))
#EndMacro
#BeginMacro(isRightF)
((0, 1)=#macro(F))
#EndMacro
